spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mh123
    url: jdbc:mysql://127.0.0.1:3306/mall?&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #告知mybatis的xml方式所要的配置文件的位置
  mapper-locations: classpath:mapper/*.xml



  #日志格式的設置：不加时间
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"



server:
  servlet:
    session:
      timeout: 12000

  port: 8081
# 12000秒


upload:
  upload-folder: E:/Vue/img-mall/uploadImg/